baseurl: /sage-lattices-EJCIM
github: https://github.com/defeo
github_base: https://github.com/defeo/sage-lattices-EJCIM
github_blob: https://github.com/defeo/sage-lattices-EJCIM/blob/master
permalink: /:categories/:title

markdown: kramdown
kramdown:
  parse_block_html: true
